# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: book
services:
  mariadb:
    extends:
      file: ./mariadb.yml
      service: mariadb
    profiles:
      - ''
      - prod
  jhipster-registry:
    extends:
      file: ./jhipster-registry.yml
      service: jhipster-registry
  kafka:
    extends:
      file: ./kafka.yml
      service: kafka
